version: "3.9"
services:

  janus-cloud:
    build:
      context: .
      dockerfile: Dockerfile
    image: janus-cloud
    volumes:
      - "./conf/:/home/janus/conf"
    ports:
      - "8288:8288"
      - "8188:8188"